{% set name = "tangled-up-in-unicode" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: f463a59e9beb612e7cf801e1721f4eeda9bce25496b0232f30bc3ef5bc61f5ef

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python 
    - pip
  run:
    - python 

test:
  imports:
    - tangled_up_in_unicode

about:
  home: https://github.com/dylan-profiler/tangled-up-in-unicode
  summary: "Access to the Unicode Character Database (UCD)"
  license: BSD
  license_file: LICENSE
  description: |
    This module provides access to character properties for all Unicode 
    characters, from the Unicode Character Database (UCD). This module 
    provides an alternative to Python's standard library unicodedata. 
  dev_url: https://github.com/dylan-profiler/tangled-up-in-unicode

extra:
  recipe-maintainers:
    - philip-khor
    - sbrugman
